# Copyright 2025 Niklas Glienke

commands:
  admin: true
  brevity_term: true

tasks:
  brevity_term_digest:
    enabled: true
    channel_id: 0123456789

admins:
  - name: "Test User"
    id: 0123456789
