# Copyright 2025 Niklas Glienke

commands:
  admin: true
  brevity_term: true

tasks:
  brevity_term_digest:
    enabled: true
    channel_id: 0123456789
    time: "12:00"
    timezone: "Europe/Zurich"

admins:
  - name: "Test User"
    id: 0123456789
